language: node_js
node_js:
  - "0.12"
env:
  global:
    - GH_REF: github.com/tbfe/bigpipe.js.git
    - secure: VvDxJ4zdVUpdcoYEcwS6r6JQK1C2jRvPw7bsOCGh0mK8o0mVCRuQ7PRJLy/uDVtI7n8VIdTeaRAqaZUgewYgrlhmCCQOnusfiiooZfAuGjxSKOYeocnmFMOgYl1J8g0df0f3rFxDnHca32WjiYBTr+55oALmUVXUmgjeK8yz624=
    - secure: gr1kO9iA5xqKpL4OBdGE4tZj+Vp/woTQ2GOYW9YXbyNZreORRNledLVXP3nFL55OT81KPtkY5ePtgAGjZzWZ2SBYjDBhChkWxhdlVCTR6Xg6mYa4XW3lceE37ZwK6f/f77xldtq1gCcEihwHPlYx79f3xIr/4BqTG6W4bIeTua0=
    - secure: Sl9INj+Z6RmCoIDW4aqo7OimK5qOh2ZoG7r8/+ytTU2vuZYJl1JKl+HGRuQAM3NrZqfvssEiDwMsL56rgtSOpM4KEv2VYMHwR+QovNKYusTvGC8dHld0mFB2+RkvC7TNc2uDvfIuUENq42/ajwU0vFQOfM/cRdhz1LZ9+tJxoJ0=
before_script:
  - npm install -g bower
  - bower install
  - npm install -g grunt-cli
after_success:
  - ./deploy_docs.sh
addons:
  sauce_connect: true
